- http://isystems.unist.ac.kr/teaching/machine-learning/
- http://darkpgmr.tistory.com/105
- https://wikidocs.net/4050

## Matrix(행렬)

행렬은 같은 차원의 백터를 모아둔 것입니다. 기하학적 의미에서는 두개의 백터를 한번에 표현한 것이기도 합니다. 또한 nxn 행렬은 n차원 공간에서 선형변환을 이야기하기도 하죠. 

$$
A =
\begin{bmatrix}
\mid&\mid&&\mid\\
a_{1} & a_{2} & \cdots & a_{n}\\
\mid&\mid&&\mid\\
\end{bmatrix}
$$


## Matrix-Vector Product
$$
A \in \mathbb{R}^{m \times n}, x \in \mathbb{R}^{n} \Longleftrightarrow Ax \in \mathbb{R}^{m}
$$

<br/>
Writing $A$ by rows, each entry of $Ax$ is an inner product between $x$ and a row of $A$
<br/>

$$
A =
\begin{bmatrix}
- &b_{1}^{T} & - \\
-& b_{2}^{T}&-  \\
&\vdots& \\
-& b_{m}^{T}&- 
\end{bmatrix}
,\qquad
Ax \in \mathbb{R}^{m} =
\begin{bmatrix}
b_{1}^{T}x \\
b_{2}^{T}x \\
\vdots \\
b_{m}^{T}x
\end{bmatrix}
$$

<br/>
Writing $A$ by columns, $Ax$ is a linear combination of the columns of $A$, with coefficients given by $x$
<br/>

$$
A =
\begin{bmatrix}
\mid&\mid&&\mid\\
a_{1} & a_{2} & \cdots & a_{n}\\
\mid&\mid&&\mid\\
\end{bmatrix}
,\qquad
Ax \in \mathbb{R}^{m} = \sum\limits_{i=1}^{n}a_{i}x_{i}
$$

In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,],[5,6,7,8]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.matmul(a,b))
print(np.dot(a,b))

[[ 70  80  90]
 [158 184 210]]
[[ 70  80  90]
 [158 184 210]]


## Element-wise Multiplication

- element-wise 곱셈입니다.
- multiply function and * operator

In [5]:
m = np.array([[1,2,3],[4,5,6]])
print(m)
n = m*0.25
print(n)
print("-------------------")
print(m*n)
print(np.multiply(m,n))
print("===================")
print(m.T.dot(n))

[[1 2 3]
 [4 5 6]]
[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]
-------------------
[[0.25 1.   2.25]
 [4.   6.25 9.  ]]
[[0.25 1.   2.25]
 [4.   6.25 9.  ]]
[[ 4.25  5.5   6.75]
 [ 5.5   7.25  9.  ]
 [ 6.75  9.   11.25]]


## Transpose

.T 가능을 이용해서 전치행렬을 계산 가능합니다.

- remember modified both the transpose and the original matrix, too!
- remember to condisder the transpose just as a different view of your matrix, rather than a different matrix entirely

In [6]:
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m_t = m.T

In [7]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Diagonal Matrix 

- For $d = \left[d_1,\cdots,d_n\right]^T\in \mathbb{R}^{n}$

$$
\text{diag}(d) = \mathbb{R}^{n \times n} 
= \begin{bmatrix}
d_{1}&0&\cdots&0 \\
0&d_{2}&\cdots&0 \\
\vdots&\vdots&\ddots&\vdots\\
0&0&\cdots&d_{n} \\
\end{bmatrix}
$$

- Multiplying  $A∈\mathbb{R}^{m \times n}$  by a diagonal matrix  $D∈\mathbb{R}^{n \times n}$  on the right scales the columns of  A  

$$
AD = 
\begin{bmatrix}
\mid&\mid&&\mid\\
d_{1}a_{1} & d_{2}a_{2} & \cdots & d_{n}a_{n}\\
\mid&\mid&&\mid\\
\end{bmatrix}
$$

In [13]:
d = np.array([10, 12, 33])
D = np.diag(d)
D

array([[10,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 33]])

In [9]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

## 역행렬

$$
A =
\begin{bmatrix}
4 & -5 \\
-2 & 3
\end{bmatrix}
, \quad
x =
\begin{bmatrix}
x_{1} \\
x_{2}
\end{bmatrix}
, \quad
b =
\begin{bmatrix}
-13 \\
9
\end{bmatrix}
$$
<br>


$$
\begin{align*}
Ax &= b \\
A^{-1}Ax &= A^{-1}b \\
x &= A^{-1}b
\end{align*}
$$

In [12]:
A = np.array([[4, -5],
              [-2, 3]])
b = np.array([[-13],
              [9]])

In [13]:
np.linalg.inv(A)

array([[1.5, 2.5],
       [1. , 2. ]])

In [11]:
x = np.linalg.inv(A).dot(b)
x

array([[3.],
       [5.]])

## Linear Transformation

아래 조건을 만족하는 매핑 함수 $T$를 Linear하다고 정의합니다.

- 임의의 두 벡터 $v,w$에 대해 $T(v+w)=T(v)+T(w)$
- 임의의 스칼라 $a$와 벡터 $v$에 대해 $T(av) = aT(v)$
- 임의의 스칼라 $c,d$와 벡터 $u,v$에 대해 $T(cu+dv) = cT(u) + dT(v)$

이는 $Ax=b$를 선형변환으로 이해할 수도 있습니다. 행렬 $A$ 가 $m$x$n$ 크기이고, $x$가 $n$차원, $b$가 $m$차원 벡터라고 할 때, 행렬 $A$는 $n$차원 벡터 $x$를 $m$차원 벡터 $b$로 변환하는 함수인 것입니다

<img src="png/19.2.png" width="500px">

<img style ="float:left" src="png/19.3.png" width="200px">

$
T(x)=\begin{bmatrix} 1 & -3 \\ 3 & 5 \\ -1 & 7 \end{bmatrix}\begin{bmatrix} { x }_{ 1 } \\ { x }_{ 2 } \end{bmatrix}
$

2차원 벡터 (2,-1)은 3차원 벡터 5,1,-9로 변환되는 것입니다.

## Matrix and Transformation

원점을 이동하지 않는 선형 좌표 변환은 행렬을 곱하여 구할 수 있다.


$$
M=
\begin{bmatrix}
m_{11} & m_{12} & m_{13}\\
m_{21} & m_{22} & m_{23}\\
m_{31} & m_{32} & m_{33}\\
\end{bmatrix}
$$
<br/>

$$
\begin{array}\
\text{Given} & & \text{Interpret}\\
\text{Transformation} & \longrightarrow & \text{matrix}\\
\text{matrix} & \longrightarrow & \text{Transformation}\\
\end{array}
$$
<br/>

$$
\begin{array}{c}\
\vec x\\
\text{input}
\end{array}
\begin{array}{c}\
\quad
\text{transformation}\\
\implies
\end{array}
\quad
\begin{array}{l}
\vec y\\
\text{output}
\end{array}
$$
<br/>

$$
\text{Transformation = rotate + stretch/compress}
$$

##### Rotation
$
\vec y = R(\theta) \vec x
$
<br/>
<img style="float:left;" src="png/linear_transform02.png" width="200px">
<br/>

<img style="float:left;" src="png/linear_transform03.png" width="200px">


$
\begin{bmatrix}
\cos(\theta)\\
\sin(\theta)
\end{bmatrix}=
R(\theta)
\begin{bmatrix}
1\\
0
\end{bmatrix}\\
$


##### Stretch & Compress
<img style="float:left;" src="png/linear_transform05.png" width="300px">
$$
\begin{array}\\
\vec y = &k\vec x\\
& \uparrow\\ 
& \text{scalar (not matrix)}\\ \\
\vec y = &k I \vec x  & \text{where } I = \text{ Identity martix}\\ \\
\vec y = &\begin{bmatrix}k&0\\0&k\end{bmatrix}\vec x
\end{array}
$$


##### Stretch & Compress
<img style="float:left;" src="png/linear_transform08.png" width="400px">
$$
\begin{array}{c}\\
& P & \\
\begin{bmatrix}x_1\\x_2\end{bmatrix} & \implies & \begin{bmatrix}x_1\\ 0\end{bmatrix}\\
\vec x & & \vec y
\end{array}
$$

$$
\vec y = P\vec x = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} x_1 \\ 0 \end{bmatrix}
$$

$$
\begin{array}\\
P \begin{bmatrix} 1 \\ 0 \end{bmatrix} & = \begin{bmatrix} 1 \\ 0 \end{bmatrix}\\
P \begin{bmatrix} 0 \\ 1 \end{bmatrix} & = \begin{bmatrix} 0 \\ 0 \end{bmatrix}\\
P \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} & = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix}
\end{array}
$$


## 고윳값과 고유백터

고유백터 : 어떠한 선형변환 A를 했을때, 그 크기만 변하고 방향이 변하지않는 벡터가 있나요?
<br>
고유값 : 그렇다면 그 크기는 얼마나 변한건가요?