* 본 문서는 모형도출을 위해 계산기로 사용하였습니다. 향후 정리할예정입니다

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import scipy.stats as sp
%matplotlib inline

In [2]:
A = [[1,1],[1,2],[1,3]]

In [4]:
x = np.matrix(A)
x

matrix([[1, 1],
        [1, 2],
        [1, 3]])

In [6]:
y= [[2,6,4]]
y= np.transpose(y)
y

array([[2],
       [6],
       [4]])

In [7]:
x.T*x

matrix([[ 3,  6],
        [ 6, 14]])

In [8]:
np.linalg.inv(x.T*x)

matrix([[ 2.33333333, -1.        ],
        [-1.        ,  0.5       ]])

In [9]:
np.linalg.inv(x.T*x)*x.T

matrix([[ 1.33333333,  0.33333333, -0.66666667],
        [-0.5       ,  0.        ,  0.5       ]])

In [10]:
beta = np.linalg.inv(x.T*x)*x.T*y
beta

matrix([[ 2.],
        [ 1.]])

In [11]:
x*beta

matrix([[ 3.],
        [ 4.],
        [ 5.]])

In [3]:
C = [[1,26.7,1.14],[1,26.9,1.41],[1,27.6,1.13],[1,26.9,1.37],[1,27.2,1.14],[1,27,1.26],[1,26.2,1.28]]

In [4]:
C

[[1, 26.7, 1.14],
 [1, 26.9, 1.41],
 [1, 27.6, 1.13],
 [1, 26.9, 1.37],
 [1, 27.2, 1.14],
 [1, 27, 1.26],
 [1, 26.2, 1.28]]

In [5]:
x=np.matrix(C)

In [6]:
y=[[87.8,87,88,87.1,87.9,87,88]]
y=np.transpose(y)

In [7]:
x.T

matrix([[  1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ],
        [ 26.7 ,  26.9 ,  27.6 ,  26.9 ,  27.2 ,  27.  ,  26.2 ],
        [  1.14,   1.41,   1.13,   1.37,   1.14,   1.26,   1.28]])

In [14]:
x.T*x

matrix([[    7.    ,   188.5   ,     8.73  ],
        [  188.5   ,  5077.15  ,   234.972 ],
        [    8.73  ,   234.972 ,    10.9671]])

In [16]:
np.linalg.inv(x.T*x)

matrix([[ 888.41039039,  -30.24486693,  -59.18846697],
        [ -30.24486693,    1.05299588,    1.51481626],
        [ -59.18846697,    1.51481626,   14.75101981]])

In [17]:
np.linalg.inv(x.T*x)*x.T

matrix([[ 13.39759104,  -8.63226842, -13.23090452,  -6.26472974,
          -1.72484242,  -2.77848507,  20.23363913],
        [ -0.40298651,   0.21661305,   0.52956161,   0.1560204 ,
           0.12351142,   0.0946902 ,  -0.71741017],
        [ -1.92671013,   2.35902848,  -0.71088569,   1.76898768,
          -1.16930199,   0.29785713,  -0.61897548]])

In [19]:
beta = np.linalg.inv(x.T*x)*x.T*y
beta

matrix([[ 102.5419763 ],
        [  -0.38347545],
        [  -3.7467023 ]])

In [21]:
x*beta

matrix([[ 88.03194106],
        [ 86.94363635],
        [ 87.72428018],
        [ 87.09350445],
        [ 87.84020334],
        [ 87.46729415],
        [ 87.69914047]])

In [16]:
beta

In [18]:
beta = np.matrix(beta)

In [8]:
y=[[87.8,87,88,87.1,87.9,87,88]]
y=np.transpose(y)

In [10]:
y.mean()

87.54285714285713

In [9]:
y-y.mean()

array([[ 0.25714286],
       [-0.54285714],
       [ 0.45714286],
       [-0.44285714],
       [ 0.35714286],
       [-0.54285714],
       [ 0.45714286]])

In [43]:
a =sp.t.cdf(4.8,96)

In [44]:
1-a

2.9117612861950803e-06

In [47]:
from scipy.stats import t
t_val = t.ppf([0.975], 96)

In [48]:
t_val

array([ 1.98498431])