# Pytorch

- Pytorch 는 Numpy를 대체하면서 GPU연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우 사용됩니다.

### 장점
- autograd 패키지는 Tensors의 모든 연산에 대해 자동 미분을 제공합니다. Define-by-run 프레임워크가 가능합니다.
- Function 클래스를 활용하여, 모든 연산과정을 encode하여 Acyclic graph를 생성합니다.

### Tensors
Tensor는 Numpy의 ndarray와 유사할 뿐만 아니라, GPU를 사용한 연산 가속도 지원합니다.

- empty : matrix를 생성합니다, 단 uninitalized되어있습니다.
- rand : matrix를 생성합니다. initalize 되어있습니다.
- zeros : 0으로 채워진 행렬을 생성합니다.
- new_ones : 1으로 채워진 텐서행렬을 생성합니다.
- tensor : tensor를 생성합니다.
- randn_like : 존재하는 tensor를 바탕으로 tensor를 생성합니다.

In [4]:
from __future__ import print_function
import torch

In [5]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29, -3.1207e-32],
        [-2.8615e-42,  1.8856e+31,  1.2712e+31],
        [ 3.2745e-12,  2.6209e+20,  2.0530e-19],
        [ 5.2938e-14,  1.6109e-19,  1.8888e+31],
        [ 4.1051e-41,  0.0000e+00,  0.0000e+00]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.3747, 0.0120, 0.5899],
        [0.5680, 0.2836, 0.4346],
        [0.3247, 0.2029, 0.3046],
        [0.7586, 0.9261, 0.7521],
        [0.4574, 0.9215, 0.0388]])


In [7]:
x = torch.zeros(5,3, dtype= torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.4784, -0.8508,  0.1735],
        [ 0.3379,  0.1394,  0.8387],
        [-2.0567, -0.1658, -0.1046],
        [ 0.1812, -1.0918,  2.0618],
        [-0.2347, -0.8838, -2.0543]])


In [16]:
print(x.size())

torch.Size([5, 3])


### Operations

In [17]:
y= torch.rand(5,3)
print(x+y)

tensor([[-0.2264, -0.1430,  0.7987],
        [ 1.3360,  0.1834,  1.5521],
        [-1.7841, -0.0012,  0.6704],
        [ 1.1281, -0.6204,  3.0044],
        [ 0.1940, -0.1261, -1.9656]])


In [18]:
print(torch.add(x,y))

tensor([[-0.2264, -0.1430,  0.7987],
        [ 1.3360,  0.1834,  1.5521],
        [-1.7841, -0.0012,  0.6704],
        [ 1.1281, -0.6204,  3.0044],
        [ 0.1940, -0.1261, -1.9656]])


In [20]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[-0.2264, -0.1430,  0.7987],
        [ 1.3360,  0.1834,  1.5521],
        [-1.7841, -0.0012,  0.6704],
        [ 1.1281, -0.6204,  3.0044],
        [ 0.1940, -0.1261, -1.9656]])

### Resizing

tensor의 크기(size)나 모양(shape)을 변경하고 싶을 때, torch.view 를 사용합니다.

In [25]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) 

In [26]:
print(x.size(),y.size(),z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.3328,  0.5744, -0.4984,  0.1375],
        [-2.4637,  0.7506,  1.2706, -0.6597],
        [-0.9510, -0.8928,  0.4991,  0.0880],
        [-0.6641, -0.5307,  0.5105,  1.5683]])
tensor([-0.3328,  0.5744, -0.4984,  0.1375, -2.4637,  0.7506,  1.2706, -0.6597,
        -0.9510, -0.8928,  0.4991,  0.0880, -0.6641, -0.5307,  0.5105,  1.5683])
tensor([[-0.3328,  0.5744, -0.4984,  0.1375, -2.4637,  0.7506,  1.2706, -0.6597],
        [-0.9510, -0.8928,  0.4991,  0.0880, -0.6641, -0.5307,  0.5105,  1.5683]])


### Tensor to Numpy

In [28]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


### Numpy to Tensor

In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Autograd

도함수를 계산하기 위해서는, tensor의 .backword()를 호출하면 됩니다. tensor가 스칼라인 경우애눈 backward에 인자를 정해줄 필요가 없습니다.

In [32]:
x = torch.ones(2,2, requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [34]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [35]:
print(y.grad_fn)

In [36]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [38]:
out.backward()

In [39]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
